### ISSUE TITLE
directML causes error in rapid orientation

### ISSUE THREAD

**Issue by ragebear00** [RapidAI/RapidOrientation#24]
rapid orientation does not work after install directML as below
The issue can be resolve only after uninstall directML and reinstall onnxruntime

   from .rapid_orientation import RapidOrientation
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\rapid_orientation\rapid_orientation.py", line 25, in <module>
    from .utils import OrtInferSession, create_operators
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\rapid_orientation\utils.py", line 10, in <module>
    from onnxruntime import (GraphOptimizationLevel, InferenceSession,
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed.

**Comment by SWHL** [comment]
The rapid orientation package has not supported the DirectML.

**Comment by ragebear00** [comment]
Understood, the rapid orientation and rapidocr directML now have a conflict. So if some one need to use 'rapid orientation', she cannot upgrade rapidocr directML.

Any chance to have two onnxruntime work at the same machine? so rapid orientation package can refer to onnxruntime, and  rapidocr directML can import onnxruntime directML

**Comment by ragebear00** [comment]
Understood, the rapid orientation and rapidocr directML now have a conflict. So if some one need to use 'rapid orientation', she cannot upgrade rapidocr directML.

Any chance to have two onnxruntime work at the same machine? so rapid orientation package can refer to onnxruntime, and  rapidocr directML can import onnxruntime directML

**Comment by SWHL** [comment]
The `onnxruntime-directml` and `onnxruntime` can't installed at the same time. Only one of them can be installed.

The solution I can think of is that rapid orientation also supports onnxruntime directml.

You can use both directml or neither at the same time.

**Comment by SWHL** [comment]
The issue has beed closed, if you have other question, please to open it.
