### ISSUE TITLE
文字少的页面，裁剪不对

### ISSUE THREAD

**Issue by SWHL** [RapidAI/RapidOrientation#29]
现在的方法是先将原图片长边缩放到256， 再剪切中间的224x224。 对于文字少的页面， 经常剪的区域不对。
我改进的方法是：
1、将原图长边缩到256，再填充边框，使得图片大小为256x256
2、再将图片resize到224x224 (将第一步的长边改为224，省掉第2步应该也是一样的）

**Comment by SWHL** [comment]
原图长边缩放到256，对于一些**较宽的图会存在文字看不清的问题**。当然，如果确定自己场景没有这种，则可以这么来改。
举例来说：
原图($1982\times270$)：
<img width="991" alt="1" src="https://github.com/user-attachments/assets/9fb668fc-cb51-4be6-9e79-7a6c8b289e64">

长边缩放到256，另一边等比缩放($256\times35$)：
![a](https://github.com/user-attachments/assets/50bda335-c527-48e5-bfaa-0c668824f0d0)

关注现有方法裁剪不到文字情况，暂时没有想到好的办法

**Comment by Joker1212** [comment]
尝试将宽高比太离谱的图切成奇数张，一起送测，取概率大的，是不是能更准确？

**Comment by Joker1212** [comment]
这个模型执行效率挺快的

**Comment by SWHL** [comment]
好主意呀。可以随机切分一个batch，一起推理得到结果，最终投票一下就行了。我改改

**Comment by SWHL** [comment]
已经在`rapid_orientation>=0.0.9`中实现了。issue先行关闭了。
